### ISSUE TITLE
书籍第22页的磁盘总量计算公式有点问题

### ISSUE THREAD

**Issue by wolfguoliang** [itnihao/zabbix-book#12]
历史数据的大小是按照90天计算出来约为 362 G ，而一年则为1.4TB ，笔者最后计算一年需要花费磁盘的总量的时候是 362 + 67 + 4 ，后两个没有问题，第一个应该是1.4TB吧？

**Comment by zhausong** [comment]
因为历史数据(history*表)会在90天后删除，故不会存储到一年

**Comment by zhausong** [comment]
@wolfguoliang 谢谢提醒，最近在写第二版，会将这些有歧义的地方描述更加准确
