### ISSUE TITLE
Zabbix_MySQLdump_per_table.sh 中的删除5天前的备份语句有问题

### ISSUE THREAD

**Issue by memoryredbook** [itnihao/zabbix-book#6]
脚本地址：https://github.com/itnihao/zabbix-book/blob/master/03-chapter/Zabbix_MySQLdump_per_table.sh

脚本中变量定义：
DATE=$(date '+%Y-%m-%d')

脚本中删除备份目录：
rm -rf $(date +%Y%m%d --date='5 days ago')

两者日期格式不一致，导致无法删除备份。

**Comment by itnihao** [comment]
@memoryredbook  已修复，谢谢反馈
