### ISSUE TITLE
some other rpm packages needed?

### ISSUE THREAD

**Issue by empo007** [itnihao/zabbix-book#9]
In order to install zabbix,we need to install php first,but when I tried to install php related packages,it failed and it said that php-common-5.3.3-3.el6_6.x86_64 was needed,but I already have php-common-5.3.3-40.el6_6.x86_64 installed.

who has the file? many thanks

**Comment by itnihao** [comment]
if you install 3.0 try it https://www.zabbix.com/documentation/3.0/manual/installation/install_from_packages/repository_installation
